language: cpp

matrix:
  include:

    # build and run all tests on Linux (compile with g++)
    - os: linux
      dist: trusty
      compiler: gcc

    # build and run all tests on Linux (compile with clang++)
    - os: linux
      dist: trusty
      compiler: clang

script:
  - ./run-tests

git:
  depth: 3

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
